to-tasty/toTasty-front

.github/ISSUE_TEMPLATE/✨-feature.md
>PR과 연관된 이슈 번호를 작성해주세요. ex) #이슈 번호, #이슈 번호
- 프로젝트 초기 세팅으로 별도 이슈 없음.
>이번 PR에서 작업한 내용들을 작성해주세요. 이미지 첨부 자유롭게!
- 이슈 템플릿 수정
- 이슈 작성 시 기본 제목 변경
>코드 리뷰 요청 및 기타 전달할 사항 등 자유롭게 작성해주세요.
- X
=> docs: 이슈 템플릿 수정

.gitignore
- close: #21 
- gitignore에 .vscode 폴더 추가
- 혹시 나중에 본인 로컬에서 .vscode 폴더가 커밋에서 제외가 안된다고 하면은 아래 방법으로 실행해보세요.
```bash
git update-index --assume-unchanged .vscode/settings.json
```
- 다시 원상복구해서 커밋에 추가하시려면 아래 방법으로 실행해보세요.
```bash
git update-index --no-assume-unchanged .vscode/settings.json
```
=> chore: gitignore .vscode 추가

package-lock.json, package.json, src/shared/model/useCountStore.ts, src/views/TestPage/TestPage.tsx
>PR과 연관된 이슈 번호를 작성해주세요. ex) #이슈 번호, #이슈 번호
- close: #31 
>이번 PR에서 작업한 내용들을 작성해주세요. 이미지 첨부 자유롭게!
- zustand 패키지 설치 및 테스트 코드 작성
- persist middleware로 전역 상태 유지
>코드 리뷰 요청 및 기타 전달할 사항 등 자유롭게 작성해주세요.
- 추가적으로 설명이 필요한 부분 있다면 꼭 말씀주세요 주석 추가하겠습니다!!
=> Feat/#31 zustand 초기 세팅

package-lock.json, src/entities/Reviews/List/api/getReviewList.ts, src/entities/Reviews/List/model/hooks/useReviewListQuery.ts, src/entities/Reviews/List/model/types.ts, src/entities/TanstackTest/api/getTanstack.ts, src/features/AxiosTest/api/patchTest.ts, src/features/AxiosTest/api/putTest.ts, src/shared/api/axiosApis.ts, src/views/AxiosApiTest/DeleteTest.tsx, src/views/AxiosApiTest/PatchTest.tsx, src/views/AxiosApiTest/PostTest.tsx, src/views/AxiosApiTest/PutTest.tsx
>PR과 연관된 이슈 번호를 작성해주세요. ex) #이슈 번호, #이슈 번호
- close: #47
>이번 PR에서 작업한 내용들을 작성해주세요. 이미지 첨부 자유롭게!
- eslint 오류 수정
- 일부 API 구현 (3차 예정)
>코드 리뷰 요청 및 기타 전달할 사항 등 자유롭게 작성해주세요.
-
=> feat: eslint 에러 발생문제 해결, 일부 API 구현

.github/workflows/dispatch-to-fork.yml, src/app/auth/kakao/page.tsx
- close: #75 
- main 브랜치에 변경사항 발생 시 배포용 레포지토리 싱크 트리거
-
=> Deploy/#75 프론트엔드 배포 자동화

.gitignore, package.json
- 로컬에서 https 환경으로 실행가능하도록 수정
-
=> [deploy] 로컬에서 https 환경으로 실행가능하도록 수정

src/features/login-with-kakao/api/loginWithKakao.ts, src/features/login-with-kakao/ui/KakaoLoginButton.tsx
- 로그인 redirect 관련 URI 방식 env관리로 변경
-
=> [refactor] 로그인 redirect 관련 URI 방식 env관리로 변경

.github/ISSUE_TEMPLATE/⚙️-chore.md, .github/ISSUE_TEMPLATE/✨-feature.md, .github/ISSUE_TEMPLATE/🐞-bug.md, .github/ISSUE_TEMPLATE/📄-docs.md, .github/ISSUE_TEMPLATE/🔨-refactor.md, .github/ISSUE_TEMPLATE/🚀-deploy.md
- close: #60 
- 이슈 템플릿 작성 시 assignee에 작성자 기본 지정
-
=> Docs: 이슈 및 pr 템플릿 수정

.github/ISSUE_TEMPLATE/⚙️-chore.md, .github/ISSUE_TEMPLATE/✨-feature.md, .github/ISSUE_TEMPLATE/🐞-bug.md, .github/ISSUE_TEMPLATE/📄-docs.md, .github/ISSUE_TEMPLATE/🔨-refactor.md, .github/ISSUE_TEMPLATE/🚀-deploy.md
- Main branch merge from dev branch (250724)
-
=> Main branch merge from dev branch (250724)

package-lock.json, package.json
=> [refactor] axios 버전 수정

src/entities/user/model/hooks/useUserStore.ts, src/entities/user/model/types.ts, src/widgets/navigation-bar/NavigationBar.tsx
- close: #115 
- isHydrated 체크 추가로 초기 렌더링 오류 수정
- 로그인하셔서 새로고침 시 로그인 버튼 보이는지 확인해주세요!!
=> fix: 로그인 버튼 깜빡임 개선

package-lock.json, package.json, src/app/home/page.tsx, src/app/page.tsx, src/entities/homeMeetingCard/index.ts, src/entities/homeMeetingCard/ui/favoriteMeetingCardArea.tsx, src/entities/homeMeetingCard/ui/newMeetingCardArea.tsx, src/entities/homeMeetingCard/ui/popularMeetingCardArea.tsx, src/entities/homeMeetingCard/ui/wishlistCardArea.tsx, src/features/edit-user-profile/model/hooks/usePatchUserProfileMutation.ts, src/features/edit-user-profile/model/types.ts, src/shared/ui/Carousel.tsx, src/shared/ui/index.ts, src/views/home/HomePage.tsx
- 피그마 다지인에 따른 홈페이지 퍼블리싱 구현
- shadcn Carousel 컴포넌트 활용
- 로그인 유무에 따른 블러처리
- 문제가 있어 보인다면 언제든지 말씀해주세요!!
=> feat/#97 홈페이지 퍼블리싱

src/app/globals.css, src/app/layout.tsx, src/shared/ui/Button.tsx, src/shared/ui/Progress.tsx, src/views/home/HomePage.tsx, src/views/login/LoginPage.tsx, src/widgets/find-meeting/ui/FindMeetingCard.tsx, src/widgets/find-meeting/ui/FindMeetingCardRow.tsx, src/widgets/find-meeting/ui/FindMeetingFilterBtns.tsx, src/widgets/find-meeting/ui/FindMeetingFilterCalendar.tsx, src/widgets/find-meeting/ui/FindMeetingPanel.tsx, src/widgets/find-meeting/ui/FindMeetingRegionSelector.tsx, src/widgets/navigation-bar/NavigationBar.tsx, src/widgets/navigation-bar/ui/LoginButton.tsx, src/widgets/navigation-bar/ui/NavigationTabs.tsx
- close: #88 
- 커스텀 컬러 색 조정
- 프로젝트 전체 적용 및 다크모드 확인 완료
- 다크모드 기능은 아직 구현전입니다.
전체 프로젝트가 구현된 이후에 다시 색조정 후 기능으로 구현할 예정입니다.
- 일단은 기존에 색 지정하시던데로 사용해주시고, 나중에 다시 전체 조정하겠습니다.
=> Refactor/#88 shadcn 커스텀 컬러 수정

src/app/test-page/page.tsx, src/features/upload-image/model/types.ts
-  image url response 변경으로 타입변경
-
=> bugfix: image url response 변경으로 타입변경

src/features/upload-image/api/postFileInfo.ts
=> feat: 이미지 파일 제한 필터링 추가

src/entities/user/model/hooks/useUserStore.ts, src/entities/user/model/types.ts, src/features/login-with-kakao/model/hooks/useLoginWithKakaoMutation.ts, src/features/logout/api/logout.ts, src/features/logout/index.ts, src/features/logout/model/hooks/useLogout.ts, src/shared/api/axiosInstance.ts, src/widgets/navigation-bar/ui/UserDropdown.tsx, src/widgets/profile-card/UserProfileCard.tsx, src/widgets/profile-card/ui/ProfileEditDialog.tsx
- Main branch merge from dev branch
-
=> Main branch merge from dev branch (250808)

src/widgets/post-meeting/PostMeetingView.tsx
- close: #188 
- 모임 작성 취소 시 뒤로가기 추가
-
=> Refactor/#188-모임 작성 취소 시 뒤로가기 추가

src/features/meetings/api/cancelJoin.ts, src/features/meetings/api/joinMeeting.ts, src/features/meetings/index.ts, src/features/meetings/model/hook/useCancelJoinMutation.ts, src/features/meetings/model/hook/useJoinMeetingMutation.ts, src/features/meetings/model/types.ts, src/views/meetings/detail/MeetingDetailPage.tsx
- close: #203 
- 모임 참여 추가/삭제 기능 구현
- 상세 페이지 버튼에 기능 적용 완료
-
=> feat: 모임 참여 추가/삭제 기능 구현 및 적용

src/entities/reviews/model/types.ts
- close: #207 
- ReviewList 필드명인 content를 reviews로 변경하여 서버 응답과 일치
- ReviewContent 인터페이스에 thumbnailUrl 필드 추가
-
=> fix: ReviewList 필드명 content -> reviews로 변경하여 서버 응답과 일치

src/entities/reviews/model/types.ts
- close: #212 
- 서버 응답 DTO 변경에 따라 ReviewContent에 reviewDate 필드 추가
-
=> feat: 서버 응답 DTO 변경에 따라 ReviewContent에 reviewDate 필드 추가

src/entities/homeMeetingCard/ui/dummyCardArea.tsx, src/views/login/LoginPage.tsx
- close: #217 
- thumbnailUrl 주소 변경
- 로그인 페이지 높이 조정
-
=> Bugfix/#217 잔버그 수정

src/views/meetings/detail/MeetingDetailPage.tsx, src/widgets/reviews/index.ts, src/widgets/reviews/ui/ReviewImgCardRow.tsx
=> feat: 상세페이지 시음리스트 추가

src/app/providers/AuthProvider.tsx, src/shared/api/axiosInstance.ts
- Main branch merge from dev branch (250813)
-
=> Main branch merge from dev branch (250813)
